### ISSUE TITLE
Leading space - possible solution?

### ISSUE THREAD

**Issue by tomchadwin** [thisisparker/choochoobot#7]
http://www.fileformat.info/info/unicode/char/2800/index.htm

I've seen tweets which use this for leading space.

**Comment by thisisparker** [comment]
Hi @tomchadwin! After a very long gap, I've refactored @choochoobot and incorporated this suggestion. I did a total rewrite so I didn't use your PR verbatim, but I did use the character you suggested. Thanks for the tip!

Closed by deafb5601d535dfde5e21664d384e04f238f2af8

**Comment by tomchadwin** [comment]
I may weep a little.
